### ISSUE TITLE
[Feature] Github nuget worklow 

### ISSUE THREAD

**Issue by anpin** [mark-gerarts/perfect-fifth#3]
hi @mark-gerarts, I'm starting working on PR for nuget publishing. Would you object if I add dependency on [gitversion](https://github.com/GitTools/GitVersion) to provide consistent package versioning? It would [require](https://gitversion.net/docs/reference/requirements) some discipline in branch naming for consistent operation

**Comment by mark-gerarts** [comment]
No, I would not mind. In fact, it would probably be a good thing to enforce some consistency. I'm looking forward to the result!

**Comment by mark-gerarts** [comment]
Right, what I do on my local machine is 

```
cd github-pages
python3 -m venv venv
. venv/bin/activate
pip install -r requirements.txt
```

This is only needed once. Then I run `./scripts/build-and-serve-site.sh` in one terminal to host the static site on localhost:8000. In another terminal window I run `npm run test:e2e`, which basically goes to every page and checks if a JS error occurs.

I am not sure how this flow would even work in a CI environment. For now, it might be okay to omit the running of tests in the workflow. They don't add that much value anyway, since most errors caught this way would result in a compilation/build error anyway. What do you think?

In any case I believe that a rewrite to fsx is a good idea. I only picked python because I knew I could set up the script fast that way.

**Comment by mark-gerarts** [comment]
Hi @anpin, I have a question regarding GitVersion. I have done a few merge commits on master since the PR was merged, but the version does not get incremented. See the [Github action output](https://github.com/mark-gerarts/perfect-fifth/actions/runs/4588874343/jobs/8103387419):

```
Successfully created package '/home/runner/work/perfect-fifth/perfect-fifth/result/PerfectFifth.0.1.0.nupkg'.
```

It keeps using version 0.1.0. Could it be that we're doing something wrong?
